### ISSUE TITLE
Plus signs are removed from arguments and replaced with spaces

### ISSUE THREAD

**Issue by ctessum** [ctessum/gobra#18]
In the current version example, when I run the command dummy/run/add with the argument "--num1=1+" and "--num2=1", it shows this in the GUI window as expected: 

`→ dummy run add --config="./conf.toml" --inBackground="false" --num1="1+" --num2="1"`

However, the terminal shows this message:

`Executing:  [dummy run add] map[config:[./conf.toml] inBackground:[false] num1:[1 ] num2:[1]]`

So it seems that somewhere the "1+" is getting converted into "1 ". 

Obviously, it doesn't make a big difference in this particular example, but in InMAP it causes problems.

**Comment by khoin** [comment]
Chris,

Check if this has been fixed with the fix at https://github.com/ctessum/gobra/pull/19

On my machine this is the log:
`Executing:  [dummy run add] map[config:[./conf.toml] inBackground:[false] num1:[1+] num2:[1]]
I must run before any subcommand runs`

Explanation:
The "+" (or any other symbols) weren't encoded before sending back to the server, so when the server receives a "+", it thought of it as a space. This is fixed by encoding the parameters with `encodeURIComponent` which is a built-in function. This is a fix on the client-side.
